AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    AWS sam app

    App for number of registered package for postal box for sam-app

Globals:
    Function:
        Timeout: 20
        MemorySize: 512
        Environment:
          Variables:
            TABLE_NAME: !Ref ProductsTable
            ENDPOINT_OVERRIDE: ""

Resources:
  GetProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/package-service-1.0.0.jar
      Handler: com.postnl.handler.GetProductHandler::handleRequest
      Runtime: java8
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ProductsTable
      Events:
        GetProduct:
          Type: Api
          Properties:
            Path: /products/{product_id}
            Method: get
  GetProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/package-service-1.0.0.jar
      Handler: com.postnl.handler.GetProductsHandler::handleRequest
      Runtime: java8
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ProductsTable
      Events:
        GetProducts:
          Type: Api
          Properties:
            Path: /products
            Method: get
  CreateProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/package-service-1.0.0.jar
      Handler: com.postnl.handler.CreateProductHandler::handleRequest
      Runtime: java8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
      Events:
        CreateProduct:
          Type: Api
          Properties:
            Path: /products
            Method: post

  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: products_table
      AttributeDefinitions:
        - AttributeName: productId
          AttributeType: S
      KeySchema:
        - AttributeName: productId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
    HelloWorldApi:
      Description: "API Gateway endpoint URL for Prod stage for Hello World function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

    GetProductFunction:
      Description: "GetProduct Lambda Function ARN"
      Value: !GetAtt GetProductFunction.Arn

    GetProductsFunction:
      Description: "GetProducts Lambda Function ARN"
      Value: !GetAtt GetProductsFunction.Arn

    CreateProductFunction:
      Description: "CreateProduct Lambda Function ARN"
      Value: !GetAtt CreateProductFunction.Arn
